#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd
# f1:USERNAME f2:PASSWORD f3:USERID f4:GROUPID f5:UIF f6:HOME f7:COMMAND
while IFS= read -r line
do
    username=$(echo "$line" | cut -f 1 -d ':')
    password=$(echo "$line" | cut -f 2 -d ':')
    userID=$(echo "$line" | cut -f 3 -d ':')
    groupID=$(echo "$line" | cut -f 4 -d ':')
    userINFO=$(echo "$line" | cut -f 5 -d ':')
    home=$(echo "$line" | cut -f 6 -d ':')
    command=$(echo "$line" | cut -f 7 -d ':')


    echo -n "The user $username is part of the $groupID gang, "
    echo -n "lives in $home and rides $command."
    echo -n " $userID's place is protected by the passcode $password, "
    echo "more info about the user here: $userINFO"
done < "/etc/passwd"
